"""Reproducible artifact generator for G4 / Module A.7: runs the deterministic
Safety Rail against all 10 seeded prescriptions and writes a system-generated
results file a reviewer can read directly, with no test suite required.

This script does NOT touch the candidate's own predicted/expected values in
data/seed_prescriptions_template.csv (the candidate_rail_output_state /
candidate_evidence_note columns) -- it only reads that file for the
prescriptions and writes ITS OWN, separately-named output file so the two are
never confused: the template holds what the candidate expected BEFORE
running anything; eval_results/seeded_rail_outputs.csv holds what the code
actually produced when run. Reuses run_safety_rail() and the ingest loaders
exactly as-is -- no rail or ingestion logic is duplicated here.

Usage:
    python -m scripts.run_seed_rail [--out PATH]
"""
from __future__ import annotations
import argparse
import csv
import json
import sys
from pathlib import Path

from src.config import REPO_ROOT
from src.db.connection import get_connection, migrate
from src.module_a.ingest.cdci_loader import load_cdci
from src.module_a.ingest.interaction_loader import load_severe_interactions
from src.module_a.ingest.pharmacy_loader import load_pharmacy_stock
from src.module_a.ingest.reference_loader import load_jan_aushadhi, load_nlem
from src.module_a.rail.engine import run_safety_rail
from src.module_a.rail.prescription_resolver import load_seed_prescriptions
from src.module_a.regulatory.loader import load_regulatory_events

DEFAULT_OUT = REPO_ROOT / "eval_results" / "seeded_rail_outputs.csv"

HEADER_COMMENT = (
    "# SYSTEM-GENERATED by scripts/run_seed_rail.py -- do not hand-edit.\n"
    "# This is what the deterministic Safety Rail actually produced for each\n"
    "# seeded prescription on this run. It is NOT the candidate's prediction:\n"
    "# the candidate's own expected/predicted values, filled in before this\n"
    "# script was ever run, are in data/seed_prescriptions_template.csv\n"
    "# (candidate_rail_output_state / candidate_evidence_note columns).\n"
)

FIELDNAMES = ["rx_id", "check_name", "system_state", "system_severity",
              "system_evidence", "system_rule_version", "system_data_versions", "as_of_date"]


def _ensure_module_a_loaded(conn) -> None:
    """Idempotent: every loader below detects an unchanged source file via
    file_hash and skips re-inserting (see DESIGN.md D-006), so calling this
    against an already-loaded DB is safe and cheap. Identical to what
    src/module_a/ingest/run_all.py does -- reused, not duplicated."""
    load_cdci(conn)
    load_nlem(conn)
    load_jan_aushadhi(conn)
    load_severe_interactions(conn)
    load_regulatory_events(conn)
    load_pharmacy_stock(conn)


def generate(conn, out_path: Path) -> list[dict]:
    by_rx = load_seed_prescriptions()
    rows = []
    for rx_id, item_rows in by_rx.items():
        result = run_safety_rail(conn, rx_id, item_rows)
        for check_name, check_results in result.items():
            for r in check_results:
                rows.append({
                    "rx_id": rx_id,
                    "check_name": check_name,
                    "system_state": r["state"],
                    "system_severity": r["severity"] or "",
                    "system_evidence": json.dumps(r["evidence"], sort_keys=True),
                    "system_rule_version": r["rule_version"],
                    "system_data_versions": json.dumps(r["data_versions"], sort_keys=True),
                    "as_of_date": r["as_of_date"],
                })
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="") as f:
        f.write(HEADER_COMMENT)
        writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    conn = get_connection()
    migrate(conn)
    _ensure_module_a_loaded(conn)
    rows = generate(conn, args.out)
    n_rx = len(load_seed_prescriptions())
    conn.close()

    print(f"Wrote {len(rows)} check results for {n_rx} seed prescriptions to {args.out}")


if __name__ == "__main__":
    sys.exit(main())
